apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokevault-auth
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pokevault-auth
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: pokevault-auth
  template:
    metadata:
      labels:
        app: pokevault-auth
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: 5001
              name: http
          envFrom:
            - configMapRef:
                name: pokevault-config
            - secretRef:
                name: pokevault-secret
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.auth.probes.liveness.path }}
              port: 5001
            initialDelaySeconds: {{ .Values.auth.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.auth.probes.readiness.path }}
              port: 5001
            initialDelaySeconds: {{ .Values.auth.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.readiness.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pokevault-auth
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    app: pokevault-auth
