apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokevault-catalog
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pokevault-catalog
spec:
  replicas: {{ .Values.catalog.replicaCount }}
  selector:
    matchLabels:
      app: pokevault-catalog
  template:
    metadata:
      labels:
        app: pokevault-catalog
    spec:
      containers:
        - name: catalog
          image: "{{ .Values.catalog.image.repository }}:{{ .Values.catalog.image.tag }}"
          imagePullPolicy: {{ .Values.catalog.image.pullPolicy }}
          ports:
            - containerPort: 5002
              name: http
          envFrom:
            - configMapRef:
                name: pokevault-config
            - secretRef:
                name: pokevault-secret
          resources:
            {{- toYaml .Values.catalog.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.catalog.probes.liveness.path }}
              port: 5002
            initialDelaySeconds: {{ .Values.catalog.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.catalog.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.catalog.probes.readiness.path }}
              port: 5002
            initialDelaySeconds: {{ .Values.catalog.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.catalog.probes.readiness.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pokevault-catalog
spec:
  type: {{ .Values.catalog.service.type }}
  ports:
    - port: {{ .Values.catalog.service.port }}
      targetPort: 5002
      protocol: TCP
      name: http
  selector:
    app: pokevault-catalog
{{- if .Values.catalog.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pokevault-catalog-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pokevault-catalog
  minReplicas: {{ .Values.catalog.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.catalog.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.catalog.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
