apiVersion: v1
kind: ConfigMap
metadata:
  name: pokevault-config
  namespace: {{ .Values.global.namespace }}
data:
  NODE_ENV: {{ .Values.global.environment }}
  MYSQL_HOST: "pokevault-mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "pokevault"
  REDIS_HOST: "pokevault-redis"
  REDIS_PORT: "6379"
  CATALOG_SERVICE_URL: "http://catalog-service:5002"
---
apiVersion: v1
kind: Secret
metadata:
  name: pokevault-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  MYSQL_USER: "pokevault"
  MYSQL_PASSWORD: "pokevault_secret"
  MYSQL_ROOT_PASSWORD: "root_super_secret"
  ADMIN_SECRET_KEY: "pokevaultadmin123"
