apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokevault-order
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pokevault-order
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app: pokevault-order
  template:
    metadata:
      labels:
        app: pokevault-order
    spec:
      containers:
        - name: order
          image: "{{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}"
          imagePullPolicy: {{ .Values.order.image.pullPolicy }}
          ports:
            - containerPort: 5003
              name: http
          envFrom:
            - configMapRef:
                name: pokevault-config
            - secretRef:
                name: pokevault-secret
          resources:
            {{- toYaml .Values.order.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.order.probes.liveness.path }}
              port: 5003
            initialDelaySeconds: {{ .Values.order.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.order.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.order.probes.readiness.path }}
              port: 5003
            initialDelaySeconds: {{ .Values.order.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.order.probes.readiness.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pokevault-order
spec:
  type: {{ .Values.order.service.type }}
  ports:
    - port: {{ .Values.order.service.port }}
      targetPort: 5003
      protocol: TCP
      name: http
  selector:
    app: pokevault-order
