{
 "title": "PokéVault Microservices — RED Observability Dashboard",
 "tags": [
  "pokevault",
  "devops",
  "microservices"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate (RPS - Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (job)",
     "legendFormat": "{{job}} RPS"
    }
   ]
  },
  {
   "title": "Error Rate (5xx - Errors)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[1m])) by (job) / sum(rate(http_requests_total[1m])) by (job) * 100",
     "legendFormat": "{{job}} Error %"
    }
   ]
  },
  {
   "title": "Latency p95 (Duration in Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, job))",
     "legendFormat": "{{job}} p95"
    }
   ]
  },
  {
   "title": "Redis Cache Hit vs Miss Ratio (Catalog Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(cache_hits_total[1m]))",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "sum(rate(cache_misses_total[1m]))",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Successful Orders Placed Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(orders_created_total{status=\"success\"})",
     "legendFormat": "Orders Count"
    }
   ]
  }
 ]
}