apiVersion: v2
name: pokevault
description: Production-grade Umbrella Helm Chart for PokéVault Cloud-Native Microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservices
  - ecommerce
  - redis
  - devops
  - gitops
maintainers:
  - name: PokéVault DevOps Team
